# Generated by Django 3.1.1 on 2020-09-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0002_auto_20200909_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routines',
        ),
    ]
