# Generated by Django 3.1.1 on 2020-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0004_books_routines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='books_description',
            field=models.TextField(),
        ),
    ]
