# Generated by Django 3.1.1 on 2020-09-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0007_books_routines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='books_description',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='routines',
            name='description_routine',
            field=models.CharField(max_length=255),
        ),
    ]
