# Generated by Django 3.1.1 on 2020-09-12 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0008_auto_20200910_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='books_uploader_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=205),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routines',
            name='uploader_routine_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=205),
            preserve_default=False,
        ),
    ]
