# Generated by Django 3.1.1 on 2020-09-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributor', '0009_auto_20200912_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routines',
            old_name='description_routine',
            new_name='routine_description',
        ),
        migrations.RenameField(
            model_name='routines',
            old_name='uploader_routine_name',
            new_name='routine_uploader_name',
        ),
    ]
